### ISSUE TITLE
Error at vtkhdf5

### ISSUE THREAD

**Issue by claretb** [dicehub/EmVTK#1]
While building, I encountered an error at the vtkhdf5 stage. I tried it on Windows and Ubuntu on virtual machine but I saw same problem.
Error:
```
FAILED: ThirdParty/hdf5/vtkhdf5/H5Tinit.c
cmd.exe /C "cd /D C:\Users\ExtremePACS\Desktop\FILES\Build\EmVTK\VTK-build\ThirdParty\hdf5\vtkhdf5\src && C:\Users\ExtremePACS\emsdk\node\12.9.1_64bit\bin\node.exe C:/Users/ExtremePACS/Desktop/FILES/Build/EmVTK/VTK-build/bin/vtkH5detect.js > C:/Users/ExtremePACS/Desktop/FILES/Build/EmVTK/VTK-build/ThirdParty/hdf5/vtkhdf5/H5Tinit.c"
Calling stub instead of signal()
Calling stub instead of raise()
raise() returning an error as we do not support it
Calling stub instead of raise()
Calling stub instead of raise()
Calling stub instead of raise()
Calling stub instead of raise()
Calling stub instead of signal()
 `M' bit.        Any bit
of a floating-point value not falling into one
of these categories is printed as a question
mark.  Bits of integer types are printed as
`I' for 2's complement and `U' for magnitude.

If the most significant bit of the normalized
mantissa (always a `1' except for `0.0') is
not stored then an `implicit=yes' appears
under the field description.  In thie case,
the radix point is still assumed to be
before the first `M' but after the implicit
bit.
nt has an associated
bias which can be subtracted to find the
true exponent.  The radix point is assumed
to be before the first `M' bit.  Any bit
of a floating-point value not falling into one
of these categories is printed as a question
mark.  Bits of integer types are printed as
`I' for 2's complement and `U' for magnitude.

If the most significant bit of the normalized
mantissa (always a `1' except for `0.0') is
not stored then an `implicit=yes' appears
under the field description.  In thie case,
the radix point is still assumed to be
before the first `M' but after the implicit
bit.
Calling stub instead of signal()
Calling stub instead of raise()
Calling stub instead of raise()
Calling stub instead of raise()
Calling stub instead of raise()
Calling stub instead of raise()
Calling stub instead of signal()
 `M' bit.        Any bit
of a floating-point value not falling into one
of these categories is printed as a question
mark.  Bits of integer types are printed as
`I' for 2's complement and `U' for magnitude.

If the most significant bit of the normalized
mantissa (always a `1' except for `0.0') is
not stored then an `implicit=yes' appears
under the field description.  In thie case,
the radix point is still assumed to be
before the first `M' but after the implicit
bit.
nt has an associated
bias which can be subtracted to find the
true exponent.  The radix point is assumed
to be before the first `M' bit.  Any bit
of a floating-point value not falling into one
of these categories is printed as a question
mark.  Bits of integer types are printed as
`I' for 2's complement and `U' for magnitude.

If the most significant bit of the normalized
mantissa (always a `1' except for `0.0') is
not stored then an `implicit=yes' appears
under the field description.  In thie case,
the radix point is still assumed to be
before the first `M' but after the implicit
bit.
Calling stub instead of signal()
Calling stub instead of raise()
Calling stub instead of raise()
Calling stub instead of raise()
Calling stub instead of raise()
Calling stub instead of raise()
Calling stub instead of signal()
 `M' bit.        Any bit
of a floating-point value not falling into one
of these categories is printed as a question
mark.  Bits of integer types are printed as
`I' for 2's complement and `U' for magnitude.

If the most significant bit of the normalized
mantissa (always a `1' except for `0.0') is
not stored then an `implicit=yes' appears
under the field description.  In thie case,
the radix point is still assumed to be
before the first `M' but after the implicit
bit.
nt has an associated
bias which can be subtracted to find the
true exponent.  The radix point is assumed
to be before the first `M' bit.  Any bit
of a floating-point value not falling into one
of these categories is printed as a question
mark.  Bits of integer types are printed as
`I' for 2's complement and `U' for magnitude.

If the most significant bit of the normalized
mantissa (always a `1' except for `0.0') is
not stored then an `implicit=yes' appears
under the field description.  In thie case,
the radix point is still assumed to be
before the first `M' but after the implicit
bit.
Calling stub instead of signal()
Calling stub instead of signal()
Calling stub instead of signal()
exception thrown: RuntimeError: memory access out of bounds,RuntimeError: memory access out of bounds
    at wasm-function[35]:1253
    at wasm-function[30]:550
    at wasm-function[45]:1
    at Object.Module._main (C:\Users\ExtremePACS\Desktop\FILES\Build\EmVTK\VTK-build\bin\vtkH5detect.js:5488:32)
    at callMain (C:\Users\ExtremePACS\Desktop\FILES\Build\EmVTK\VTK-build\bin\vtkH5detect.js:5799:30)
    at doRun (C:\Users\ExtremePACS\Desktop\FILES\Build\EmVTK\VTK-build\bin\vtkH5detect.js:5858:23)
    at run (C:\Users\ExtremePACS\Desktop\FILES\Build\EmVTK\VTK-build\bin\vtkH5detect.js:5873:5)
    at runCaller (C:\Users\ExtremePACS\Desktop\FILES\Build\EmVTK\VTK-build\bin\vtkH5detect.js:5783:19)
    at removeRunDependency (C:\Users\ExtremePACS\Desktop\FILES\Build\EmVTK\VTK-build\bin\vtkH5detect.js:1544:7)
    at receiveInstance (C:\Users\ExtremePACS\Desktop\FILES\Build\EmVTK\VTK-build\bin\vtkH5detect.js:1654:5)
```

**Comment by jourdain** [comment]
HDF5 needs to be turned off.

**Comment by claretb** [comment]
Thanks but in Docker it's working very well. Why is this happening?

**Comment by jourdain** [comment]
Are you properly doing the following?
https://github.com/dicehub/EmVTK/blob/master/Dockerfile#L4
https://github.com/dicehub/EmVTK/blob/master/Dockerfile#L6
https://github.com/dicehub/EmVTK/blob/master/Dockerfile#L24

**Comment by claretb** [comment]
Of course. Many times :)
And How can I turn off HDF5?

**Comment by jourdain** [comment]
Run the cmake-gui and look for hdf5, then turn everything that you can off.

**Comment by jourdain** [comment]
BTW, why are you building on your machine and not on docker? The docker image provide all the tools and  a valid [cmake tool file](https://github.com/dicehub/EmVTK/blob/master/Dockerfile#L14) which is most likely the issue here.

**Comment by nxsofsys** [comment]
Which version of Emscripten and VTK used?

**Comment by claretb** [comment]
> Run the cmake-gui and look for hdf5, then turn everything that you can off.

It's just VTK_USE_SYSTEM_HDF5 and already off.

> BTW, why are you building on your machine and not on docker? The docker image provide all the tools and a valid [cmake tool file](https://github.com/dicehub/EmVTK/blob/master/Dockerfile#L14) which is most likely the issue here.

Yes. I am just trying but apparently I will use Docker image.

**Comment by claretb** [comment]
> Which version of Emscripten and VTK used?

I am using 1.38.48 upstream version of Emscripten for now but I had tried latest version too.
And VTK: https://github.com/dicehub/VTK/tree/emscripten

**Comment by thewtex** [comment]
The `dockcross` Docker image contains and configures the CMake toolchain file with a `CMAKE_CROSSCOMPILING_EMULATOR`. This is used with CMake `try_run`'s. HDF5 has a few build introspection steps that do not use `try_run`'s. I updated ITK's internal HDF5 to use this, but I do not recall if I ported it to this VTK branch -- I can add it if needed.

**Comment by claretb** [comment]
A few days ago, when I tried to build ITK with Emscripten toolchain, I got the same error.
No need to add, I will probably use Docker.
